config/routes.rb
Rails.application.routes.draw do
  root 'tickets#index'
  resources :tickets
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ticket.rb
class Ticket < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController

  def index
    @tickets = Ticket.all
  end

  def delete
    Ticket.destroy(params[:id])
  end

  def new
  end

  def create
    @tickets_hash = params["features"]
    @tickets = []

    (0..4).each do |index|
      @tickets << {:name => @tickets_hash["#{index}"]["name"],
                   :description => @tickets_hash["#{index}"]["description"]}
    end

    pivotal_service = PivotalService.new(@tickets)
    pivotal_service.raise_tickets
    pivotal_service.save_tickets
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MockingRequestsTestDemo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tickets/index.html.erb
<h1>Tickets</h1>
<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Description</th>
      <th>Pivotal ID</th>
    </tr>
  </thead>
  <tbody>
    <% @tickets.each do |ticket| %>
      <tr>
        <td><%= ticket.id %></td>
        <td><%= ticket.name %></td>
        <td><%= ticket.description %></td>
        <td><%= link_to "#{ticket.pivotal_ticket_id}", "https://www.pivotaltracker.com/story/show/#{ticket.pivotal_ticket_id}", :target => "_blank" %></td>
        <td><%= link_to "Delete", ticket_path(ticket), :method => "delete" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to "Add tickets", new_ticket_path %>

app/views/tickets/new.html.erb
<h1>Add feature tickets</h1>


<%= form_tag tickets_path do %>
  <% (0..4).each do |index| %>
    <h4><%= "Ticket ##{index+1}" %></h4>
    <span>Name</span>
    <%= text_field_tag "features[#{index}][name]" %>
    <span>Description</span>
    <%= text_area_tag "features[#{index}][description]" %>
  <% end %>

  <%= submit_tag "Submit"%>
<% end %>